/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.flink.client;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2020-12-05")
public class registerJob {

	public interface Iface {

		public void registerMyJob(java.lang.String jobID, java.util.List<task> tasks) throws org.apache.thrift.TException;

	}

	public interface AsyncIface {

		public void registerMyJob(java.lang.String jobID, java.util.List<task> tasks, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler) throws org.apache.thrift.TException;

	}

	public static class Client extends org.apache.thrift.TServiceClient implements Iface {
		public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
			public Factory() {}
			public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
				return new Client(prot);
			}
			public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
				return new Client(iprot, oprot);
			}
		}

		public Client(org.apache.thrift.protocol.TProtocol prot)
		{
			super(prot, prot);
		}

		public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
			super(iprot, oprot);
		}

		public void registerMyJob(java.lang.String jobID, java.util.List<task> tasks) throws org.apache.thrift.TException
		{
			send_registerMyJob(jobID, tasks);
			recv_registerMyJob();
		}

		public void send_registerMyJob(java.lang.String jobID, java.util.List<task> tasks) throws org.apache.thrift.TException
		{
			registerMyJob_args args = new registerMyJob_args();
			args.setJobID(jobID);
			args.setTasks(tasks);
			sendBase("registerMyJob", args);
		}

		public void recv_registerMyJob() throws org.apache.thrift.TException
		{
			registerMyJob_result result = new registerMyJob_result();
			receiveBase(result, "registerMyJob");
			return;
		}

	}
	public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
		public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
			private org.apache.thrift.async.TAsyncClientManager clientManager;
			private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
			public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
				this.clientManager = clientManager;
				this.protocolFactory = protocolFactory;
			}
			public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
				return new AsyncClient(protocolFactory, clientManager, transport);
			}
		}

		public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
			super(protocolFactory, clientManager, transport);
		}

		public void registerMyJob(java.lang.String jobID, java.util.List<task> tasks, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler) throws org.apache.thrift.TException {
			checkReady();
			registerMyJob_call method_call = new registerMyJob_call(jobID, tasks, resultHandler, this, ___protocolFactory, ___transport);
			this.___currentMethod = method_call;
			___manager.call(method_call);
		}

		public static class registerMyJob_call extends org.apache.thrift.async.TAsyncMethodCall<Void> {
			private java.lang.String jobID;
			private java.util.List<task> tasks;
			public registerMyJob_call(java.lang.String jobID, java.util.List<task> tasks, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
				super(client, protocolFactory, transport, resultHandler, false);
				this.jobID = jobID;
				this.tasks = tasks;
			}

			public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
				prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("registerMyJob", org.apache.thrift.protocol.TMessageType.CALL, 0));
				registerMyJob_args args = new registerMyJob_args();
				args.setJobID(jobID);
				args.setTasks(tasks);
				args.write(prot);
				prot.writeMessageEnd();
			}

			public Void getResult() throws org.apache.thrift.TException {
				if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
					throw new java.lang.IllegalStateException("Method call not finished!");
				}
				org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
				org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
				return null;
			}
		}

	}

	public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
		private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(Processor.class.getName());
		public Processor(I iface) {
			super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
		}

		protected Processor(I iface, java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> processMap) {
			super(iface, getProcessMap(processMap));
		}

		private static <I extends Iface> java.util.Map<java.lang.String,  org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> getProcessMap(java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
			processMap.put("registerMyJob", new registerMyJob());
			return processMap;
		}

		public static class registerMyJob<I extends Iface> extends org.apache.thrift.ProcessFunction<I, registerMyJob_args> {
			public registerMyJob() {
				super("registerMyJob");
			}

			public registerMyJob_args getEmptyArgsInstance() {
				return new registerMyJob_args();
			}

			protected boolean isOneway() {
				return false;
			}

			@Override
			protected boolean handleRuntimeExceptions() {
				return false;
			}

			public registerMyJob_result getResult(I iface, registerMyJob_args args) throws org.apache.thrift.TException {
				registerMyJob_result result = new registerMyJob_result();
				iface.registerMyJob(args.jobID, args.tasks);
				return result;
			}
		}

	}

	public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
		private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(AsyncProcessor.class.getName());
		public AsyncProcessor(I iface) {
			super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
		}

		protected AsyncProcessor(I iface, java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
			super(iface, getProcessMap(processMap));
		}

		private static <I extends AsyncIface> java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
			processMap.put("registerMyJob", new registerMyJob());
			return processMap;
		}

		public static class registerMyJob<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, registerMyJob_args, Void> {
			public registerMyJob() {
				super("registerMyJob");
			}

			public registerMyJob_args getEmptyArgsInstance() {
				return new registerMyJob_args();
			}

			public org.apache.thrift.async.AsyncMethodCallback<Void> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
				final org.apache.thrift.AsyncProcessFunction fcall = this;
				return new org.apache.thrift.async.AsyncMethodCallback<Void>() {
					public void onComplete(Void o) {
						registerMyJob_result result = new registerMyJob_result();
						try {
							fcall.sendResponse(fb, result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
						} catch (org.apache.thrift.transport.TTransportException e) {
							_LOGGER.error("TTransportException writing to internal frame buffer", e);
							fb.close();
						} catch (java.lang.Exception e) {
							_LOGGER.error("Exception writing to internal frame buffer", e);
							onError(e);
						}
					}
					public void onError(java.lang.Exception e) {
						byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
						org.apache.thrift.TSerializable msg;
						registerMyJob_result result = new registerMyJob_result();
						if (e instanceof org.apache.thrift.transport.TTransportException) {
							_LOGGER.error("TTransportException inside handler", e);
							fb.close();
							return;
						} else if (e instanceof org.apache.thrift.TApplicationException) {
							_LOGGER.error("TApplicationException inside handler", e);
							msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
							msg = (org.apache.thrift.TApplicationException)e;
						} else {
							_LOGGER.error("Exception inside handler", e);
							msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
							msg = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
						}
						try {
							fcall.sendResponse(fb,msg,msgType,seqid);
						} catch (java.lang.Exception ex) {
							_LOGGER.error("Exception writing to internal frame buffer", ex);
							fb.close();
						}
					}
				};
			}

			protected boolean isOneway() {
				return false;
			}

			public void start(I iface, registerMyJob_args args, org.apache.thrift.async.AsyncMethodCallback<Void> resultHandler) throws org.apache.thrift.TException {
				iface.registerMyJob(args.jobID, args.tasks,resultHandler);
			}
		}

	}

	public static class registerMyJob_args implements org.apache.thrift.TBase<registerMyJob_args, registerMyJob_args._Fields>, java.io.Serializable, Cloneable, Comparable<registerMyJob_args>   {
		private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("registerMyJob_args");

		private static final org.apache.thrift.protocol.TField JOB_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("jobID", org.apache.thrift.protocol.TType.STRING, (short)1);
		private static final org.apache.thrift.protocol.TField TASKS_FIELD_DESC = new org.apache.thrift.protocol.TField("tasks", org.apache.thrift.protocol.TType.LIST, (short)2);

		private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new registerMyJob_argsStandardSchemeFactory();
		private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new registerMyJob_argsTupleSchemeFactory();

		public java.lang.String jobID; // required
		public java.util.List<task> tasks; // required

		/** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
		public enum _Fields implements org.apache.thrift.TFieldIdEnum {
			JOB_ID((short)1, "jobID"),
			TASKS((short)2, "tasks");

			private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

			static {
				for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
					byName.put(field.getFieldName(), field);
				}
			}

			/**
			 * Find the _Fields constant that matches fieldId, or null if its not found.
			 */
			public static _Fields findByThriftId(int fieldId) {
				switch(fieldId) {
					case 1: // JOB_ID
						return JOB_ID;
					case 2: // TASKS
						return TASKS;
					default:
						return null;
				}
			}

			/**
			 * Find the _Fields constant that matches fieldId, throwing an exception
			 * if it is not found.
			 */
			public static _Fields findByThriftIdOrThrow(int fieldId) {
				_Fields fields = findByThriftId(fieldId);
				if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
				return fields;
			}

			/**
			 * Find the _Fields constant that matches name, or null if its not found.
			 */
			public static _Fields findByName(java.lang.String name) {
				return byName.get(name);
			}

			private final short _thriftId;
			private final java.lang.String _fieldName;

			_Fields(short thriftId, java.lang.String fieldName) {
				_thriftId = thriftId;
				_fieldName = fieldName;
			}

			public short getThriftFieldId() {
				return _thriftId;
			}

			public java.lang.String getFieldName() {
				return _fieldName;
			}
		}

		// isset id assignments
		public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
		static {
			java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
			tmpMap.put(_Fields.JOB_ID, new org.apache.thrift.meta_data.FieldMetaData("jobID", org.apache.thrift.TFieldRequirementType.DEFAULT,
				new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
			tmpMap.put(_Fields.TASKS, new org.apache.thrift.meta_data.FieldMetaData("tasks", org.apache.thrift.TFieldRequirementType.DEFAULT,
				new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
					new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, task.class))));
			metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
			org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(registerMyJob_args.class, metaDataMap);
		}

		public registerMyJob_args() {
		}

		public registerMyJob_args(
			java.lang.String jobID,
			java.util.List<task> tasks)
		{
			this();
			this.jobID = jobID;
			this.tasks = tasks;
		}

		/**
		 * Performs a deep copy on <i>other</i>.
		 */
		public registerMyJob_args(registerMyJob_args other) {
			if (other.isSetJobID()) {
				this.jobID = other.jobID;
			}
			if (other.isSetTasks()) {
				java.util.List<task> __this__tasks = new java.util.ArrayList<task>(other.tasks.size());
				for (task other_element : other.tasks) {
					__this__tasks.add(new task(other_element));
				}
				this.tasks = __this__tasks;
			}
		}

		public registerMyJob_args deepCopy() {
			return new registerMyJob_args(this);
		}

		@Override
		public void clear() {
			this.jobID = null;
			this.tasks = null;
		}

		public java.lang.String getJobID() {
			return this.jobID;
		}

		public registerMyJob_args setJobID(java.lang.String jobID) {
			this.jobID = jobID;
			return this;
		}

		public void unsetJobID() {
			this.jobID = null;
		}

		/** Returns true if field jobID is set (has been assigned a value) and false otherwise */
		public boolean isSetJobID() {
			return this.jobID != null;
		}

		public void setJobIDIsSet(boolean value) {
			if (!value) {
				this.jobID = null;
			}
		}

		public int getTasksSize() {
			return (this.tasks == null) ? 0 : this.tasks.size();
		}

		public java.util.Iterator<task> getTasksIterator() {
			return (this.tasks == null) ? null : this.tasks.iterator();
		}

		public void addToTasks(task elem) {
			if (this.tasks == null) {
				this.tasks = new java.util.ArrayList<task>();
			}
			this.tasks.add(elem);
		}

		public java.util.List<task> getTasks() {
			return this.tasks;
		}

		public registerMyJob_args setTasks(java.util.List<task> tasks) {
			this.tasks = tasks;
			return this;
		}

		public void unsetTasks() {
			this.tasks = null;
		}

		/** Returns true if field tasks is set (has been assigned a value) and false otherwise */
		public boolean isSetTasks() {
			return this.tasks != null;
		}

		public void setTasksIsSet(boolean value) {
			if (!value) {
				this.tasks = null;
			}
		}

		public void setFieldValue(_Fields field, java.lang.Object value) {
			switch (field) {
				case JOB_ID:
					if (value == null) {
						unsetJobID();
					} else {
						setJobID((java.lang.String)value);
					}
					break;

				case TASKS:
					if (value == null) {
						unsetTasks();
					} else {
						setTasks((java.util.List<task>)value);
					}
					break;

			}
		}

		public java.lang.Object getFieldValue(_Fields field) {
			switch (field) {
				case JOB_ID:
					return getJobID();

				case TASKS:
					return getTasks();

			}
			throw new java.lang.IllegalStateException();
		}

		/** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
		public boolean isSet(_Fields field) {
			if (field == null) {
				throw new java.lang.IllegalArgumentException();
			}

			switch (field) {
				case JOB_ID:
					return isSetJobID();
				case TASKS:
					return isSetTasks();
			}
			throw new java.lang.IllegalStateException();
		}

		@Override
		public boolean equals(java.lang.Object that) {
			if (that == null)
				return false;
			if (that instanceof registerMyJob_args)
				return this.equals((registerMyJob_args)that);
			return false;
		}

		public boolean equals(registerMyJob_args that) {
			if (that == null)
				return false;
			if (this == that)
				return true;

			boolean this_present_jobID = true && this.isSetJobID();
			boolean that_present_jobID = true && that.isSetJobID();
			if (this_present_jobID || that_present_jobID) {
				if (!(this_present_jobID && that_present_jobID))
					return false;
				if (!this.jobID.equals(that.jobID))
					return false;
			}

			boolean this_present_tasks = true && this.isSetTasks();
			boolean that_present_tasks = true && that.isSetTasks();
			if (this_present_tasks || that_present_tasks) {
				if (!(this_present_tasks && that_present_tasks))
					return false;
				if (!this.tasks.equals(that.tasks))
					return false;
			}

			return true;
		}

		@Override
		public int hashCode() {
			int hashCode = 1;

			hashCode = hashCode * 8191 + ((isSetJobID()) ? 131071 : 524287);
			if (isSetJobID())
				hashCode = hashCode * 8191 + jobID.hashCode();

			hashCode = hashCode * 8191 + ((isSetTasks()) ? 131071 : 524287);
			if (isSetTasks())
				hashCode = hashCode * 8191 + tasks.hashCode();

			return hashCode;
		}

		@Override
		public int compareTo(registerMyJob_args other) {
			if (!getClass().equals(other.getClass())) {
				return getClass().getName().compareTo(other.getClass().getName());
			}

			int lastComparison = 0;

			lastComparison = java.lang.Boolean.valueOf(isSetJobID()).compareTo(other.isSetJobID());
			if (lastComparison != 0) {
				return lastComparison;
			}
			if (isSetJobID()) {
				lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.jobID, other.jobID);
				if (lastComparison != 0) {
					return lastComparison;
				}
			}
			lastComparison = java.lang.Boolean.valueOf(isSetTasks()).compareTo(other.isSetTasks());
			if (lastComparison != 0) {
				return lastComparison;
			}
			if (isSetTasks()) {
				lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tasks, other.tasks);
				if (lastComparison != 0) {
					return lastComparison;
				}
			}
			return 0;
		}

		public _Fields fieldForId(int fieldId) {
			return _Fields.findByThriftId(fieldId);
		}

		public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
			scheme(iprot).read(iprot, this);
		}

		public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
			scheme(oprot).write(oprot, this);
		}

		@Override
		public java.lang.String toString() {
			java.lang.StringBuilder sb = new java.lang.StringBuilder("registerMyJob_args(");
			boolean first = true;

			sb.append("jobID:");
			if (this.jobID == null) {
				sb.append("null");
			} else {
				sb.append(this.jobID);
			}
			first = false;
			if (!first) sb.append(", ");
			sb.append("tasks:");
			if (this.tasks == null) {
				sb.append("null");
			} else {
				sb.append(this.tasks);
			}
			first = false;
			sb.append(")");
			return sb.toString();
		}

		public void validate() throws org.apache.thrift.TException {
			// check for required fields
			// check for sub-struct validity
		}

		private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
			try {
				write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
			} catch (org.apache.thrift.TException te) {
				throw new java.io.IOException(te);
			}
		}

		private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
			try {
				read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
			} catch (org.apache.thrift.TException te) {
				throw new java.io.IOException(te);
			}
		}

		private static class registerMyJob_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
			public registerMyJob_argsStandardScheme getScheme() {
				return new registerMyJob_argsStandardScheme();
			}
		}

		private static class registerMyJob_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<registerMyJob_args> {

			public void read(org.apache.thrift.protocol.TProtocol iprot, registerMyJob_args struct) throws org.apache.thrift.TException {
				org.apache.thrift.protocol.TField schemeField;
				iprot.readStructBegin();
				while (true)
				{
					schemeField = iprot.readFieldBegin();
					if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
						break;
					}
					switch (schemeField.id) {
						case 1: // JOB_ID
							if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
								struct.jobID = iprot.readString();
								struct.setJobIDIsSet(true);
							} else {
								org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
							}
							break;
						case 2: // TASKS
							if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
								{
									org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
									struct.tasks = new java.util.ArrayList<task>(_list8.size);
									task _elem9;
									for (int _i10 = 0; _i10 < _list8.size; ++_i10)
									{
										_elem9 = new task();
										_elem9.read(iprot);
										struct.tasks.add(_elem9);
									}
									iprot.readListEnd();
								}
								struct.setTasksIsSet(true);
							} else {
								org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
							}
							break;
						default:
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					iprot.readFieldEnd();
				}
				iprot.readStructEnd();

				// check for required fields of primitive type, which can't be checked in the validate method
				struct.validate();
			}

			public void write(org.apache.thrift.protocol.TProtocol oprot, registerMyJob_args struct) throws org.apache.thrift.TException {
				struct.validate();

				oprot.writeStructBegin(STRUCT_DESC);
				if (struct.jobID != null) {
					oprot.writeFieldBegin(JOB_ID_FIELD_DESC);
					oprot.writeString(struct.jobID);
					oprot.writeFieldEnd();
				}
				if (struct.tasks != null) {
					oprot.writeFieldBegin(TASKS_FIELD_DESC);
					{
						oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.tasks.size()));
						for (task _iter11 : struct.tasks)
						{
							_iter11.write(oprot);
						}
						oprot.writeListEnd();
					}
					oprot.writeFieldEnd();
				}
				oprot.writeFieldStop();
				oprot.writeStructEnd();
			}

		}

		private static class registerMyJob_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
			public registerMyJob_argsTupleScheme getScheme() {
				return new registerMyJob_argsTupleScheme();
			}
		}

		private static class registerMyJob_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<registerMyJob_args> {

			@Override
			public void write(org.apache.thrift.protocol.TProtocol prot, registerMyJob_args struct) throws org.apache.thrift.TException {
				org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
				java.util.BitSet optionals = new java.util.BitSet();
				if (struct.isSetJobID()) {
					optionals.set(0);
				}
				if (struct.isSetTasks()) {
					optionals.set(1);
				}
				oprot.writeBitSet(optionals, 2);
				if (struct.isSetJobID()) {
					oprot.writeString(struct.jobID);
				}
				if (struct.isSetTasks()) {
					{
						oprot.writeI32(struct.tasks.size());
						for (task _iter12 : struct.tasks)
						{
							_iter12.write(oprot);
						}
					}
				}
			}

			@Override
			public void read(org.apache.thrift.protocol.TProtocol prot, registerMyJob_args struct) throws org.apache.thrift.TException {
				org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
				java.util.BitSet incoming = iprot.readBitSet(2);
				if (incoming.get(0)) {
					struct.jobID = iprot.readString();
					struct.setJobIDIsSet(true);
				}
				if (incoming.get(1)) {
					{
						org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
						struct.tasks = new java.util.ArrayList<task>(_list13.size);
						task _elem14;
						for (int _i15 = 0; _i15 < _list13.size; ++_i15)
						{
							_elem14 = new task();
							_elem14.read(iprot);
							struct.tasks.add(_elem14);
						}
					}
					struct.setTasksIsSet(true);
				}
			}
		}

		private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
			return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
		}
	}

	public static class registerMyJob_result implements org.apache.thrift.TBase<registerMyJob_result, registerMyJob_result._Fields>, java.io.Serializable, Cloneable, Comparable<registerMyJob_result>   {
		private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("registerMyJob_result");


		private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new registerMyJob_resultStandardSchemeFactory();
		private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new registerMyJob_resultTupleSchemeFactory();


		/** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
		public enum _Fields implements org.apache.thrift.TFieldIdEnum {
			;

			private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

			static {
				for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
					byName.put(field.getFieldName(), field);
				}
			}

			/**
			 * Find the _Fields constant that matches fieldId, or null if its not found.
			 */
			public static _Fields findByThriftId(int fieldId) {
				switch(fieldId) {
					default:
						return null;
				}
			}

			/**
			 * Find the _Fields constant that matches fieldId, throwing an exception
			 * if it is not found.
			 */
			public static _Fields findByThriftIdOrThrow(int fieldId) {
				_Fields fields = findByThriftId(fieldId);
				if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
				return fields;
			}

			/**
			 * Find the _Fields constant that matches name, or null if its not found.
			 */
			public static _Fields findByName(java.lang.String name) {
				return byName.get(name);
			}

			private final short _thriftId;
			private final java.lang.String _fieldName;

			_Fields(short thriftId, java.lang.String fieldName) {
				_thriftId = thriftId;
				_fieldName = fieldName;
			}

			public short getThriftFieldId() {
				return _thriftId;
			}

			public java.lang.String getFieldName() {
				return _fieldName;
			}
		}
		public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
		static {
			java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
			metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
			org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(registerMyJob_result.class, metaDataMap);
		}

		public registerMyJob_result() {
		}

		/**
		 * Performs a deep copy on <i>other</i>.
		 */
		public registerMyJob_result(registerMyJob_result other) {
		}

		public registerMyJob_result deepCopy() {
			return new registerMyJob_result(this);
		}

		@Override
		public void clear() {
		}

		public void setFieldValue(_Fields field, java.lang.Object value) {
			switch (field) {
			}
		}

		public java.lang.Object getFieldValue(_Fields field) {
			switch (field) {
			}
			throw new java.lang.IllegalStateException();
		}

		/** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
		public boolean isSet(_Fields field) {
			if (field == null) {
				throw new java.lang.IllegalArgumentException();
			}

			switch (field) {
			}
			throw new java.lang.IllegalStateException();
		}

		@Override
		public boolean equals(java.lang.Object that) {
			if (that == null)
				return false;
			if (that instanceof registerMyJob_result)
				return this.equals((registerMyJob_result)that);
			return false;
		}

		public boolean equals(registerMyJob_result that) {
			if (that == null)
				return false;
			if (this == that)
				return true;

			return true;
		}

		@Override
		public int hashCode() {
			int hashCode = 1;

			return hashCode;
		}

		@Override
		public int compareTo(registerMyJob_result other) {
			if (!getClass().equals(other.getClass())) {
				return getClass().getName().compareTo(other.getClass().getName());
			}

			int lastComparison = 0;

			return 0;
		}

		public _Fields fieldForId(int fieldId) {
			return _Fields.findByThriftId(fieldId);
		}

		public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
			scheme(iprot).read(iprot, this);
		}

		public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
			scheme(oprot).write(oprot, this);
		}

		@Override
		public java.lang.String toString() {
			java.lang.StringBuilder sb = new java.lang.StringBuilder("registerMyJob_result(");
			boolean first = true;

			sb.append(")");
			return sb.toString();
		}

		public void validate() throws org.apache.thrift.TException {
			// check for required fields
			// check for sub-struct validity
		}

		private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
			try {
				write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
			} catch (org.apache.thrift.TException te) {
				throw new java.io.IOException(te);
			}
		}

		private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
			try {
				read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
			} catch (org.apache.thrift.TException te) {
				throw new java.io.IOException(te);
			}
		}

		private static class registerMyJob_resultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
			public registerMyJob_resultStandardScheme getScheme() {
				return new registerMyJob_resultStandardScheme();
			}
		}

		private static class registerMyJob_resultStandardScheme extends org.apache.thrift.scheme.StandardScheme<registerMyJob_result> {

			public void read(org.apache.thrift.protocol.TProtocol iprot, registerMyJob_result struct) throws org.apache.thrift.TException {
				org.apache.thrift.protocol.TField schemeField;
				iprot.readStructBegin();
				while (true)
				{
					schemeField = iprot.readFieldBegin();
					if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
						break;
					}
					switch (schemeField.id) {
						default:
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
					}
					iprot.readFieldEnd();
				}
				iprot.readStructEnd();

				// check for required fields of primitive type, which can't be checked in the validate method
				struct.validate();
			}

			public void write(org.apache.thrift.protocol.TProtocol oprot, registerMyJob_result struct) throws org.apache.thrift.TException {
				struct.validate();

				oprot.writeStructBegin(STRUCT_DESC);
				oprot.writeFieldStop();
				oprot.writeStructEnd();
			}

		}

		private static class registerMyJob_resultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
			public registerMyJob_resultTupleScheme getScheme() {
				return new registerMyJob_resultTupleScheme();
			}
		}

		private static class registerMyJob_resultTupleScheme extends org.apache.thrift.scheme.TupleScheme<registerMyJob_result> {

			@Override
			public void write(org.apache.thrift.protocol.TProtocol prot, registerMyJob_result struct) throws org.apache.thrift.TException {
				org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
			}

			@Override
			public void read(org.apache.thrift.protocol.TProtocol prot, registerMyJob_result struct) throws org.apache.thrift.TException {
				org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
			}
		}

		private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
			return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
		}
	}

}
