/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.apache.flink.client;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2020-12-05")
public class task implements org.apache.thrift.TBase<task, task._Fields>, java.io.Serializable, Cloneable, Comparable<task> {
	private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("task");

	private static final org.apache.thrift.protocol.TField UUID_FIELD_DESC = new org.apache.thrift.protocol.TField("uuid", org.apache.thrift.protocol.TType.STRING, (short)1);
	private static final org.apache.thrift.protocol.TField JOB_VERTEX_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("JobVertexID", org.apache.thrift.protocol.TType.STRING, (short)2);
	private static final org.apache.thrift.protocol.TField DEP_FIELD_DESC = new org.apache.thrift.protocol.TField("dep", org.apache.thrift.protocol.TType.LIST, (short)3);

	private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new taskStandardSchemeFactory();
	private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new taskTupleSchemeFactory();

	public java.lang.String uuid; // required
	public java.lang.String JobVertexID; // required
	public java.util.List<java.lang.String> dep; // required

	/** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
	public enum _Fields implements org.apache.thrift.TFieldIdEnum {
		UUID((short)1, "uuid"),
		JOB_VERTEX_ID((short)2, "JobVertexID"),
		DEP((short)3, "dep");

		private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

		static {
			for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
				byName.put(field.getFieldName(), field);
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, or null if its not found.
		 */
		public static _Fields findByThriftId(int fieldId) {
			switch(fieldId) {
				case 1: // UUID
					return UUID;
				case 2: // JOB_VERTEX_ID
					return JOB_VERTEX_ID;
				case 3: // DEP
					return DEP;
				default:
					return null;
			}
		}

		/**
		 * Find the _Fields constant that matches fieldId, throwing an exception
		 * if it is not found.
		 */
		public static _Fields findByThriftIdOrThrow(int fieldId) {
			_Fields fields = findByThriftId(fieldId);
			if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
			return fields;
		}

		/**
		 * Find the _Fields constant that matches name, or null if its not found.
		 */
		public static _Fields findByName(java.lang.String name) {
			return byName.get(name);
		}

		private final short _thriftId;
		private final java.lang.String _fieldName;

		_Fields(short thriftId, java.lang.String fieldName) {
			_thriftId = thriftId;
			_fieldName = fieldName;
		}

		public short getThriftFieldId() {
			return _thriftId;
		}

		public java.lang.String getFieldName() {
			return _fieldName;
		}
	}

	// isset id assignments
	public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
	static {
		java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
		tmpMap.put(_Fields.UUID, new org.apache.thrift.meta_data.FieldMetaData("uuid", org.apache.thrift.TFieldRequirementType.DEFAULT,
			new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
		tmpMap.put(_Fields.JOB_VERTEX_ID, new org.apache.thrift.meta_data.FieldMetaData("JobVertexID", org.apache.thrift.TFieldRequirementType.DEFAULT,
			new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
		tmpMap.put(_Fields.DEP, new org.apache.thrift.meta_data.FieldMetaData("dep", org.apache.thrift.TFieldRequirementType.DEFAULT,
			new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
				new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
		metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
		org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(task.class, metaDataMap);
	}

	public task() {
	}

	public task(
		java.lang.String uuid,
		java.lang.String JobVertexID,
		java.util.List<java.lang.String> dep)
	{
		this();
		this.uuid = uuid;
		this.JobVertexID = JobVertexID;
		this.dep = dep;
	}

	/**
	 * Performs a deep copy on <i>other</i>.
	 */
	public task(task other) {
		if (other.isSetUuid()) {
			this.uuid = other.uuid;
		}
		if (other.isSetJobVertexID()) {
			this.JobVertexID = other.JobVertexID;
		}
		if (other.isSetDep()) {
			java.util.List<java.lang.String> __this__dep = new java.util.ArrayList<java.lang.String>(other.dep);
			this.dep = __this__dep;
		}
	}

	public task deepCopy() {
		return new task(this);
	}

	@Override
	public void clear() {
		this.uuid = null;
		this.JobVertexID = null;
		this.dep = null;
	}

	public java.lang.String getUuid() {
		return this.uuid;
	}

	public task setUuid(java.lang.String uuid) {
		this.uuid = uuid;
		return this;
	}

	public void unsetUuid() {
		this.uuid = null;
	}

	/** Returns true if field uuid is set (has been assigned a value) and false otherwise */
	public boolean isSetUuid() {
		return this.uuid != null;
	}

	public void setUuidIsSet(boolean value) {
		if (!value) {
			this.uuid = null;
		}
	}

	public java.lang.String getJobVertexID() {
		return this.JobVertexID;
	}

	public task setJobVertexID(java.lang.String JobVertexID) {
		this.JobVertexID = JobVertexID;
		return this;
	}

	public void unsetJobVertexID() {
		this.JobVertexID = null;
	}

	/** Returns true if field JobVertexID is set (has been assigned a value) and false otherwise */
	public boolean isSetJobVertexID() {
		return this.JobVertexID != null;
	}

	public void setJobVertexIDIsSet(boolean value) {
		if (!value) {
			this.JobVertexID = null;
		}
	}

	public int getDepSize() {
		return (this.dep == null) ? 0 : this.dep.size();
	}

	public java.util.Iterator<java.lang.String> getDepIterator() {
		return (this.dep == null) ? null : this.dep.iterator();
	}

	public void addToDep(java.lang.String elem) {
		if (this.dep == null) {
			this.dep = new java.util.ArrayList<java.lang.String>();
		}
		this.dep.add(elem);
	}

	public java.util.List<java.lang.String> getDep() {
		return this.dep;
	}

	public task setDep(java.util.List<java.lang.String> dep) {
		this.dep = dep;
		return this;
	}

	public void unsetDep() {
		this.dep = null;
	}

	/** Returns true if field dep is set (has been assigned a value) and false otherwise */
	public boolean isSetDep() {
		return this.dep != null;
	}

	public void setDepIsSet(boolean value) {
		if (!value) {
			this.dep = null;
		}
	}

	public void setFieldValue(_Fields field, java.lang.Object value) {
		switch (field) {
			case UUID:
				if (value == null) {
					unsetUuid();
				} else {
					setUuid((java.lang.String)value);
				}
				break;

			case JOB_VERTEX_ID:
				if (value == null) {
					unsetJobVertexID();
				} else {
					setJobVertexID((java.lang.String)value);
				}
				break;

			case DEP:
				if (value == null) {
					unsetDep();
				} else {
					setDep((java.util.List<java.lang.String>)value);
				}
				break;

		}
	}

	public java.lang.Object getFieldValue(_Fields field) {
		switch (field) {
			case UUID:
				return getUuid();

			case JOB_VERTEX_ID:
				return getJobVertexID();

			case DEP:
				return getDep();

		}
		throw new java.lang.IllegalStateException();
	}

	/** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
	public boolean isSet(_Fields field) {
		if (field == null) {
			throw new java.lang.IllegalArgumentException();
		}

		switch (field) {
			case UUID:
				return isSetUuid();
			case JOB_VERTEX_ID:
				return isSetJobVertexID();
			case DEP:
				return isSetDep();
		}
		throw new java.lang.IllegalStateException();
	}

	@Override
	public boolean equals(java.lang.Object that) {
		if (that == null)
			return false;
		if (that instanceof task)
			return this.equals((task)that);
		return false;
	}

	public boolean equals(task that) {
		if (that == null)
			return false;
		if (this == that)
			return true;

		boolean this_present_uuid = true && this.isSetUuid();
		boolean that_present_uuid = true && that.isSetUuid();
		if (this_present_uuid || that_present_uuid) {
			if (!(this_present_uuid && that_present_uuid))
				return false;
			if (!this.uuid.equals(that.uuid))
				return false;
		}

		boolean this_present_JobVertexID = true && this.isSetJobVertexID();
		boolean that_present_JobVertexID = true && that.isSetJobVertexID();
		if (this_present_JobVertexID || that_present_JobVertexID) {
			if (!(this_present_JobVertexID && that_present_JobVertexID))
				return false;
			if (!this.JobVertexID.equals(that.JobVertexID))
				return false;
		}

		boolean this_present_dep = true && this.isSetDep();
		boolean that_present_dep = true && that.isSetDep();
		if (this_present_dep || that_present_dep) {
			if (!(this_present_dep && that_present_dep))
				return false;
			if (!this.dep.equals(that.dep))
				return false;
		}

		return true;
	}

	@Override
	public int hashCode() {
		int hashCode = 1;

		hashCode = hashCode * 8191 + ((isSetUuid()) ? 131071 : 524287);
		if (isSetUuid())
			hashCode = hashCode * 8191 + uuid.hashCode();

		hashCode = hashCode * 8191 + ((isSetJobVertexID()) ? 131071 : 524287);
		if (isSetJobVertexID())
			hashCode = hashCode * 8191 + JobVertexID.hashCode();

		hashCode = hashCode * 8191 + ((isSetDep()) ? 131071 : 524287);
		if (isSetDep())
			hashCode = hashCode * 8191 + dep.hashCode();

		return hashCode;
	}

	@Override
	public int compareTo(task other) {
		if (!getClass().equals(other.getClass())) {
			return getClass().getName().compareTo(other.getClass().getName());
		}

		int lastComparison = 0;

		lastComparison = java.lang.Boolean.valueOf(isSetUuid()).compareTo(other.isSetUuid());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetUuid()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.uuid, other.uuid);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = java.lang.Boolean.valueOf(isSetJobVertexID()).compareTo(other.isSetJobVertexID());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetJobVertexID()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.JobVertexID, other.JobVertexID);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		lastComparison = java.lang.Boolean.valueOf(isSetDep()).compareTo(other.isSetDep());
		if (lastComparison != 0) {
			return lastComparison;
		}
		if (isSetDep()) {
			lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.dep, other.dep);
			if (lastComparison != 0) {
				return lastComparison;
			}
		}
		return 0;
	}

	public _Fields fieldForId(int fieldId) {
		return _Fields.findByThriftId(fieldId);
	}

	public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
		scheme(iprot).read(iprot, this);
	}

	public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
		scheme(oprot).write(oprot, this);
	}

	@Override
	public java.lang.String toString() {
		java.lang.StringBuilder sb = new java.lang.StringBuilder("task(");
		boolean first = true;

		sb.append("uuid:");
		if (this.uuid == null) {
			sb.append("null");
		} else {
			sb.append(this.uuid);
		}
		first = false;
		if (!first) sb.append(", ");
		sb.append("JobVertexID:");
		if (this.JobVertexID == null) {
			sb.append("null");
		} else {
			sb.append(this.JobVertexID);
		}
		first = false;
		if (!first) sb.append(", ");
		sb.append("dep:");
		if (this.dep == null) {
			sb.append("null");
		} else {
			sb.append(this.dep);
		}
		first = false;
		sb.append(")");
		return sb.toString();
	}

	public void validate() throws org.apache.thrift.TException {
		// check for required fields
		// check for sub-struct validity
	}

	private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
		try {
			write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
		} catch (org.apache.thrift.TException te) {
			throw new java.io.IOException(te);
		}
	}

	private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
		try {
			read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
		} catch (org.apache.thrift.TException te) {
			throw new java.io.IOException(te);
		}
	}

	private static class taskStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
		public taskStandardScheme getScheme() {
			return new taskStandardScheme();
		}
	}

	private static class taskStandardScheme extends org.apache.thrift.scheme.StandardScheme<task> {

		public void read(org.apache.thrift.protocol.TProtocol iprot, task struct) throws org.apache.thrift.TException {
			org.apache.thrift.protocol.TField schemeField;
			iprot.readStructBegin();
			while (true)
			{
				schemeField = iprot.readFieldBegin();
				if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
					break;
				}
				switch (schemeField.id) {
					case 1: // UUID
						if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
							struct.uuid = iprot.readString();
							struct.setUuidIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					case 2: // JOB_VERTEX_ID
						if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
							struct.JobVertexID = iprot.readString();
							struct.setJobVertexIDIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					case 3: // DEP
						if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
							{
								org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
								struct.dep = new java.util.ArrayList<java.lang.String>(_list0.size);
								java.lang.String _elem1;
								for (int _i2 = 0; _i2 < _list0.size; ++_i2)
								{
									_elem1 = iprot.readString();
									struct.dep.add(_elem1);
								}
								iprot.readListEnd();
							}
							struct.setDepIsSet(true);
						} else {
							org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
						}
						break;
					default:
						org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
				}
				iprot.readFieldEnd();
			}
			iprot.readStructEnd();

			// check for required fields of primitive type, which can't be checked in the validate method
			struct.validate();
		}

		public void write(org.apache.thrift.protocol.TProtocol oprot, task struct) throws org.apache.thrift.TException {
			struct.validate();

			oprot.writeStructBegin(STRUCT_DESC);
			if (struct.uuid != null) {
				oprot.writeFieldBegin(UUID_FIELD_DESC);
				oprot.writeString(struct.uuid);
				oprot.writeFieldEnd();
			}
			if (struct.JobVertexID != null) {
				oprot.writeFieldBegin(JOB_VERTEX_ID_FIELD_DESC);
				oprot.writeString(struct.JobVertexID);
				oprot.writeFieldEnd();
			}
			if (struct.dep != null) {
				oprot.writeFieldBegin(DEP_FIELD_DESC);
				{
					oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.dep.size()));
					for (java.lang.String _iter3 : struct.dep)
					{
						oprot.writeString(_iter3);
					}
					oprot.writeListEnd();
				}
				oprot.writeFieldEnd();
			}
			oprot.writeFieldStop();
			oprot.writeStructEnd();
		}

	}

	private static class taskTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
		public taskTupleScheme getScheme() {
			return new taskTupleScheme();
		}
	}

	private static class taskTupleScheme extends org.apache.thrift.scheme.TupleScheme<task> {

		@Override
		public void write(org.apache.thrift.protocol.TProtocol prot, task struct) throws org.apache.thrift.TException {
			org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
			java.util.BitSet optionals = new java.util.BitSet();
			if (struct.isSetUuid()) {
				optionals.set(0);
			}
			if (struct.isSetJobVertexID()) {
				optionals.set(1);
			}
			if (struct.isSetDep()) {
				optionals.set(2);
			}
			oprot.writeBitSet(optionals, 3);
			if (struct.isSetUuid()) {
				oprot.writeString(struct.uuid);
			}
			if (struct.isSetJobVertexID()) {
				oprot.writeString(struct.JobVertexID);
			}
			if (struct.isSetDep()) {
				{
					oprot.writeI32(struct.dep.size());
					for (java.lang.String _iter4 : struct.dep)
					{
						oprot.writeString(_iter4);
					}
				}
			}
		}

		@Override
		public void read(org.apache.thrift.protocol.TProtocol prot, task struct) throws org.apache.thrift.TException {
			org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
			java.util.BitSet incoming = iprot.readBitSet(3);
			if (incoming.get(0)) {
				struct.uuid = iprot.readString();
				struct.setUuidIsSet(true);
			}
			if (incoming.get(1)) {
				struct.JobVertexID = iprot.readString();
				struct.setJobVertexIDIsSet(true);
			}
			if (incoming.get(2)) {
				{
					org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
					struct.dep = new java.util.ArrayList<java.lang.String>(_list5.size);
					java.lang.String _elem6;
					for (int _i7 = 0; _i7 < _list5.size; ++_i7)
					{
						_elem6 = iprot.readString();
						struct.dep.add(_elem6);
					}
				}
				struct.setDepIsSet(true);
			}
		}
	}

	private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
		return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
	}
}

